name: Deployment

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v4
        with:
         go-version: '1.24'
         check-latest: true
      - name: install dependencies
        run: go mod download
      - name: build
        run: make build
      - name: copy files via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "mecha.dev, templates/*, content/*, public/*, .git/refs/heads/main"
          target: /app
      - name: restart server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: sudo systemctl restart ${{ secrets.DEPLOY_RESTART_SERVICE }}
