name: Deploy
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v4
        with:
         go-version: '1.24'
         check-latest: true
      - name: install dependencies
        run: go mod download
      - name: build
        run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: server binary
          path: mecha.dev
