name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v4
        with:
         go-version: '1.24'
         check-latest: true
      - name: install dependencies
        run: go mod download
      - name: run tests
        run: make test
